In [5]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import reuters
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense
from tensorflow.keras.callbacks import EarlyStopping


In [3]:
#Load dataset and keep upto 10000 words
max_words = 10000
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words = max_words)
x_train[0]

[1,
 2,
 2,
 8,
 43,
 10,
 447,
 5,
 25,
 207,
 270,
 5,
 3095,
 111,
 16,
 369,
 186,
 90,
 67,
 7,
 89,
 5,
 19,
 102,
 6,
 19,
 124,
 15,
 90,
 67,
 84,
 22,
 482,
 26,
 7,
 48,
 4,
 49,
 8,
 864,
 39,
 209,
 154,
 6,
 151,
 6,
 83,
 11,
 15,
 22,
 155,
 11,
 15,
 7,
 48,
 9,
 4579,
 1005,
 504,
 6,
 258,
 6,
 272,
 11,
 15,
 22,
 134,
 44,
 11,
 15,
 16,
 8,
 197,
 1245,
 90,
 67,
 52,
 29,
 209,
 30,
 32,
 132,
 6,
 109,
 15,
 17,
 12]

In [8]:
#Pad sequences
max_len = 200
x_train = pad_sequences(x_train, maxlen=max_len)
x_test = pad_sequences(x_test, maxlen=max_len)


In [9]:
print("Train shape:", x_train, "Test_shape:", x_test)

Train shape: [[  0   0   0 ...  15  17  12]
 [  0   0   0 ... 505  17  12]
 [  0   0   0 ...  11  17  12]
 ...
 [  0   0   0 ... 407  17  12]
 [  0   0   0 ... 364  17  12]
 [  0   0   0 ... 113  17  12]] Test_shape: [[   0    0    0 ...  510   17   12]
 [   4   96 1043 ...  760   17   12]
 [   7 2775   33 ...    8   17   12]
 ...
 [   0    0    0 ...   11   17   12]
 [   0    0    0 ...    8   17   12]
 [   4  377  101 ... 1523   17   12]]


In [17]:
#Setup the Sequential Simple Rnn()
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=128, input_length=500 ))
model.add(SimpleRNN(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

/home/kushal/Projects/GenAi/Simple_Rnn/venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#Create an instance of early stopping callback
earlystopping=EarlyStopping(monitor='accuracy', patience=5, restore_best_weights=True)
earlystopping

In [16]:
#Train the model
history=model.fit(x_train,y_train,epochs=10,batch_size=32,validation_split=.2,callbacks=[earlystopping])

Epoch 1/10


225/225 ━━━━━━━━━━━━━━━━━━━━ 14s 60ms/step - accuracy: 0.0081 - loss: nan - val_accuracy: 0.0056 - val_loss: nan
Epoch 2/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - accuracy: 0.0066 - loss: nan - val_accuracy: 0.0056 - val_loss: nan
Epoch 3/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - accuracy: 0.0068 - loss: nan - val_accuracy: 0.0056 - val_loss: nan
Epoch 4/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - accuracy: 0.0052 - loss: nan - val_accuracy: 0.0056 - val_loss: nan
Epoch 5/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - accuracy: 0.0064 - loss: nan - val_accuracy: 0.0056 - val_loss: nan
Epoch 6/10
225/225 ━━━━━━━━━━━━━━━━━━━━ 13s 59ms/step - accuracy: 0.0072 - loss: nan - val_accuracy: 0.0056 - val_loss: nan
